---
title: "Inital data analysis for FINDONOR- CHANGES IN SELF-RATED HEALTH DURING THE STUDY AND IT'S RELATION TO IRON BIOMARKERS "
author: "Mikko Arvasr"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
    df_print: paged

---



```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
library(tidyverse)
#library(epitools)
#library(ez)
library(lubridate)
#library(ggbeeswarm)
#library(tidymodels)
#library(broom)
#library(GGally)
#library(ggfortify)
#library(car)
#library(boot)
```

# Executive summary

This file includes the code for computing the regression results regarding the predictors of the evolution of self-related health during the FinDonor study for the 
# Load the data

We load the data from hypothesis based regressions and initial data analysis and combine them together. 

```{r loading}
#Load questionnaire data recoded to change
load(file = "../results/changedata.rdata") 


#Load data used in hypothesis regressions
load(file = "../results/hypregdata.rdata")

```




```{r}
logit_pre_menop_women <- glm(health_outcome ~ age + starting_weight + BMI_diff + 
                               log_Ferritin_beginning + Hb_beginning +
                              donation_frequency + health_very_good + health_excellent,
                             data=regression_data_pre_menop_women,
                            family="binomial")
 
 summary(logit_pre_menop_women)
```

```{r}
plot(logit_pre_menop_women)
```

```{r}
vif(logit_pre_menop_women)
```

```{r}
tidy_logit_pre_menop_women <-
  logit_pre_menop_women %>% 
  tidy %>% 
  mutate(OR = exp(estimate),
         group = "Pre_menopause_women")
```

